version: '3'

services:
  backend:
    container_name: my-flask-backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - my_network

  frontend:
    container_name: my-react-frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=4173
      - BACKEND_URL=http://my-flask-backend:5000
    depends_on:
      - backend
    networks:
      - my_network
 
networks:
  my_network:
