version: '3'

services:
  backend:
    container_name: my-flask-backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9100:9100"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - my_network

  frontend:
    container_name: my-react-frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=4173
      - BACKEND_URL=http://my-flask-backend:5000
    depends_on:
      - backend
    networks:
      - my_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.33.5
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
  
  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
 
networks:
  my_network:
