apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: custom-port
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP